GhostfolioSidekick/CurrencyHelper.cs
GhostfolioSidekick/CurrencyPair.cs
GhostfolioSidekick/Ghostfolio/API/GhostfolioAPI.cs
GhostfolioSidekick/Model/Currency.cs

Enable known currency conversions (GBP -> GBp) when one is not available

---

GhostfolioSidekick/AccountMaintainer/AccountMaintainerTask.cs
GhostfolioSidekick/FileImporter/FileImporterTask.cs
GhostfolioSidekick/Ghostfolio/API/GhostfolioAPI.cs
GhostfolioSidekick/MarketDataMaintainer/Actions/CreateManualSymbol.cs
GhostfolioSidekick/MarketDataMaintainer/CreateManualSymbolTask.cs

- Clean up code
- Ignore Unitprice of 0

Fix ManualSymbols

---

ConsoleHelper/Program.cs
GhostfolioSidekick.UnitTests/FileImporter/Bitvavo/BitvavoParserTests.cs
GhostfolioSidekick.UnitTests/FileImporter/CryptoWorkaroundsTests.cs
GhostfolioSidekick.UnitTests/FileImporter/Nexo/NexoParserTests.cs
GhostfolioSidekick/Configuration/ConfigurationInstance.cs
GhostfolioSidekick/Configuration/Settings.cs
GhostfolioSidekick/FileImporter/Bitvavo/BitvavoParser.cs
GhostfolioSidekick/FileImporter/CryptoRecordBaseImporter.cs
GhostfolioSidekick/FileImporter/CryptoWorkarounds.cs
GhostfolioSidekick/FileImporter/Nexo/NexoParser.cs
GhostfolioSidekick/Model/Money.cs
README.md

- Remove Dust from the overview
- Add workaround for Stake rewards

Improve crypto

---

GhostfolioSidekick/Configuration/Settings.cs
GhostfolioSidekick/DisplayInformationTask.cs
GhostfolioSidekick/Ghostfolio/API/GhostfolioAPI.cs
GhostfolioSidekick/MarketDataMaintainer/Actions/CreateManualSymbol.cs
README.md

Allow priority setting of DataSource

---

GhostfolioSidekick.UnitTests/FileImporter/Bitvavo/BitvavoParserTests.cs
GhostfolioSidekick.UnitTests/FileImporter/DeGiro/DeGiroParserNLTests.cs
GhostfolioSidekick.UnitTests/FileImporter/DeGiro/DeGiroParserPTTests.cs
GhostfolioSidekick.UnitTests/FileImporter/Generic/GenericParserTests.cs
GhostfolioSidekick.UnitTests/FileImporter/Nexo/NexoParserTests.cs
GhostfolioSidekick.UnitTests/FileImporter/ScalableCapital/ScalableCapitalParserTests.cs
GhostfolioSidekick.UnitTests/FileImporter/Trading212/Trading212Tests.cs
GhostfolioSidekick/Configuration/ConfigurationInstance.cs
GhostfolioSidekick/Ghostfolio/API/GhostfolioAPI.cs
GhostfolioSidekick/Ghostfolio/API/IGhostfolioAPI.cs
GhostfolioSidekick/MarketDataMaintainer/Actions/CreateManualSymbol.cs
GhostfolioSidekick/MarketDataMaintainer/MarketDataMaintainerTask.cs
README.md

Allow setting benchmarks from config

---

GhostfolioSidekick.UnitTests/FileImporter/Generic/GenericParserTests.cs
GhostfolioSidekick.UnitTests/FileImporter/TestFiles/Generic/CashTransactions/single_dividend.csv
GhostfolioSidekick.UnitTests/GhostfolioSidekick.UnitTests.csproj
GhostfolioSidekick/FileImporter/Generic/GenericParser.cs
GhostfolioSidekick/FileImporter/Generic/GenericRecord.cs
README.md

Add support for taxes in the generic parser

---

.github/workflows/clean-up-pr-images.yml
.github/workflows/docker-publish.yml
README.md

Publish Docker images on PR. Clone of #98

---

GhostfolioSidekick/Configuration/Settings.cs
GhostfolioSidekick/DisplayInformationTask.cs
GhostfolioSidekick/MarketDataMaintainer/MarketDataMaintainerTask.cs
README.md

Allow configuration to Delete unused symbols

---

GhostfolioAPI/API/Mapper/ContractToModelMapper.cs
GhostfolioAPI/API/MarketDataService.cs
GhostfolioAPI/IMarketDataService.cs
GhostfolioSidekick.UnitTests/FileImporter/FileImporterTaskTests.cs
GhostfolioSidekick.UnitTests/MarketDataMaintainer/DeleteUnusedSymbolsTaskTests.cs
GhostfolioSidekick.UnitTests/MarketDataMaintainer/SetTrackingInsightOnSymbolsTaskTests.cs
GhostfolioSidekick/FileImporter/FileImporterTask.cs
GhostfolioSidekick/MarketDataMaintainer/DeleteUnusedSymbolsTask.cs

TODO: Check why the cache is being cleared constantly

Misc fixes

---

Configuration/Settings.cs
Cryptocurrency.UnitTests/AddStakeRewardsToPreviousBuyActivityTests.cs
Cryptocurrency.UnitTests/ApplyDustCorrectionWorkaroundTests.cs
Cryptocurrency/AddStakeRewardsToPreviousBuyActivity.cs
Cryptocurrency/ApplyDustCorrectionWorkaround.cs
GhostfolioSidekick.UnitTests/DisplayInformationTaskTests.cs
GhostfolioSidekick.UnitTests/TimedHostedServiceTests.cs
GhostfolioSidekick/DisplayInformationTask.cs
GhostfolioSidekick/Program.cs
Model/Strategies/StrategiesPriority.cs
README.md

should close #187 eventually
[x] Dust 
[x] Stake rewards
[] small cachbacks should also be added -> postpone to a future PR

Fix crypto workarounds

---

Configuration/ApplicationSettings.cs
Configuration/IApplicationSettings.cs
GhostfolioAPI/API/RestCall.cs
GhostfolioAPI/API/RestCallOptions.cs
GhostfolioSidekick/DisplayInformationTask.cs
GhostfolioSidekick/Program.cs
README.md

Implement the ability to specify a wait between calls to Ghostfolio API

Implement trottling

---

Configuration.UnitTests/ApplicationSettingsTests.cs
GhostfolioAPI.UnitTests/API/Mapper/ContractToModelMapperTests.cs
GhostfolioAPI.UnitTests/Strategies/AddStakeRewardsToPreviousBuyActivityTests.cs
GhostfolioAPI.UnitTests/Strategies/RoundStrategyTests.cs
GhostfolioAPI.UnitTests/Strategies/StockSplitStrategyTests.cs
GhostfolioAPI/BalanceCalculator.cs
GhostfolioAPI/Contract/BalanceList.cs
GhostfolioAPI/Strategies/AddStakeRewardsToPreviousBuyActivity.cs
GhostfolioAPI/Strategies/ApiStrategyBase.cs
GhostfolioAPI/Strategies/ApplyDustCorrection.cs
GhostfolioAPI/Strategies/DeterminePrice.cs
GhostfolioAPI/Strategies/IHoldingStrategy.cs
GhostfolioAPI/Strategies/NotNativeSupportedTransactionsInGhostfolio.cs
GhostfolioAPI/Strategies/RoundStrategy.cs
GhostfolioAPI/Strategies/StockSplitStrategy.cs
GhostfolioAPI/Strategies/StrategiesPriority.cs
GhostfolioSidekick.UnitTests/FileImporter/FileImporterTaskTests.cs
GhostfolioSidekick/FileImporter/FileImporterTask.cs
GhostfolioSidekick/Program.cs
IntegrationTests/Run.cs
IntegrationTests/TestLogger.cs
Model.UnitTests/Compare/MergeActivitiesTests.cs
Model.UnitTests/CompareUtilitiesTests.cs
Model/Compare/MergeActivities.cs
Model/Compare/MergeOrder.cs
Parsers.UnitTests/CurrencyToolsTests.cs
Parsers.UnitTests/DeGiro/DeGiroRecordNLTests.cs
Parsers.UnitTests/DeGiro/DeGiroRecordPTTests.cs
Parsers/ScalableCaptial/ScalableCapitalPrimeParser.cs

- Moved strategies to 1 place Namespace fixes
- Filter out empty transaction
- Do not ignored rounded difference, but try to add it somewhere
- Assumeprice, also use the next of prev day in case it is missing

Small fixes

---

Parsers.UnitTests/DeGiro/DeGiroParserENTests.cs
Parsers.UnitTests/Parsers.UnitTests.csproj
Parsers.UnitTests/TestFiles/DeGiro/EN/BuyOrders/single_buy_marketfund.csv
Parsers.UnitTests/TestFiles/DeGiro/EN/CashTransactions/single_dividend_marketfund.csv
Parsers.UnitTests/TestFiles/DeGiro/EN/SellOrders/single_sell_marketfund.csv
Parsers/DeGiro/DeGiroParserBase.cs
Parsers/DeGiro/DeGiroRecordEN.cs

DeGiro English MarketFunds

---

GhostfolioSidekick.UnitTests/ProgramTests.cs
GhostfolioSidekick/Program.cs

Oops, I just realised the parser wasn't actually registered in the main Program yet, sorry :sweat_smile:
Mind merging this hotfix real quick? :innocent:

Add German Trade Republic Parser to Program.cs

---

.github/workflows/docker-publish.yml
README.md

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VibeNL/GhostfolioSidekick/pull/361?shareId=b7329290-ce1f-4e6d-91c4-6ac5659a070b).

Update Docker image tag to v1

---

.github/workflows/docker-publish.yml

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VibeNL/GhostfolioSidekick/pull/366?shareId=c9f08c28-c26f-4b68-a926-6bd05f54667d).

Update Docker tags to v2

---

.github/workflows/docker-publish.yml
Configuration.UnitTests/Configuration.UnitTests.csproj
Configuration/Configuration.csproj
Cryptocurrency.UnitTests/Cryptocurrency.UnitTests.csproj
Cryptocurrency/Cryptocurrency.csproj
Database.UnitTests/Database.UnitTests.csproj
Database/Database.csproj
ExternalDataProvider.UnitTests/ExternalDataProvider.UnitTests.csproj
ExternalDataProvider/ExternalDataProvider.csproj
GhostfolioAPI.UnitTests/GhostfolioAPI.UnitTests.csproj
GhostfolioAPI/GhostfolioAPI.csproj
GhostfolioSidekick.UnitTests/GhostfolioSidekick.UnitTests.csproj
GhostfolioSidekick/Dockerfile
GhostfolioSidekick/GhostfolioSidekick.csproj
Model.UnitTests/Model.UnitTests.csproj
Parsers.UnitTests/Parsers.UnitTests.csproj
Parsers/Parsers.csproj
Tools/ScraperUtilities/ScraperUtilities.csproj

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VibeNL/GhostfolioSidekick/pull/369?shareId=d4089606-ada6-44b7-b935-0e6c1bb11ceb).

Upgrade to .NET 9

---

Configuration.UnitTests/Configuration.UnitTests.csproj
Cryptocurrency.UnitTests/Cryptocurrency.UnitTests.csproj
Database.UnitTests/Database.UnitTests.csproj
ExternalDataProvider.UnitTests/ExternalDataProvider.UnitTests.csproj
GhostfolioAPI.UnitTests/GhostfolioAPI.UnitTests.csproj
GhostfolioSidekick.UnitTests/GhostfolioSidekick.UnitTests.csproj
Model.UnitTests/Model.UnitTests.csproj
Parsers.UnitTests/Parsers.UnitTests.csproj

Package replacement in unit tests.
Replaced the `FluentAssertions` package with the `AwesomeAssertions` package in multiple unit test project files.
- `Configuration.UnitTests.csproj`: Replaced `FluentAssertions` with `AwesomeAssertions`.
- `Cryptocurrency.UnitTests.csproj`: Replaced `FluentAssertions` with `AwesomeAssertions`.
- `Database.UnitTests.csproj`: Replaced `FluentAssertions` with `AwesomeAssertions`.
- `ExternalDataProvider.UnitTests.csproj`: Replaced `FluentAssertions` with `AwesomeAssertions`.
- `GhostfolioAPI.UnitTests.csproj`: Replaced `FluentAssertions` with `AwesomeAssertions`.

Replaced the `FluentAssertions` package with the `AwesomeAssertions`

---

IntegrationTests/IntegrationTestBasic.cs

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VibeNL/GhostfolioSidekick/pull/412?shareId=8cf1c401-b041-4fc5-8310-a3eaf34baf28).

Add a custom network in the integration test

---

Parsers/Generic/GenericParser.cs

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VibeNL/GhostfolioSidekick/pull/416?shareId=0fcff86c-2817-4fca-b4df-f84673858810).

Fix generic parser to handle quantity of 0 for withdrawal and deposit

---

GhostfolioSidekick/appsettings.json
PortfolioViewer/PortfolioViewer.ApiService/appsettings.json

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VibeNL/GhostfolioSidekick/pull/473?shareId=e7570607-2372-48c6-be19-7e852f104f7c).

Fix HTTPS endpoint for webserver inside Docker container

---

PortfolioViewer/PortfolioViewer.WASM/Components/Chat/ChatOverlay.razor

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/VibeNL/GhostfolioSidekick/pull/479?shareId=41866fc1-347b-4dcc-97e4-835d65fc9534).

Extend the markdig implementation to support tables

---

ExternalDataProvider/CoinGecko/CoinGeckoRepository.cs
ExternalDataProvider/Yahoo/YahooRepository.cs
GhostfolioAPI/API/ApiWrapper.cs
GhostfolioAPI/API/Compare/MergeActivities.cs
GhostfolioAPI/API/Mapper/ContractToModelMapper.cs
GhostfolioAPI/GhostfolioMarketData.cs
GhostfolioAPI/GhostfolioSymbolMatcher.cs
GhostfolioAPI/GhostfolioSync.cs
GhostfolioSidekick.UnitTests/Activities/DetermineHoldingsTests.cs
GhostfolioSidekick.UnitTests/Activities/SymbolMatcherTaskTests.cs
GhostfolioSidekick/AccountMaintainer/BalanceCalculator.cs
GhostfolioSidekick/Activities/ActivityManager.cs
GhostfolioSidekick/Activities/DetermineHoldings.cs
GhostfolioSidekick/Activities/SymbolMatcherTask.cs
GhostfolioSidekick/MarketDataMaintainer/MarketDataStockSplitTask.cs
IntegrationTests/IntegrationTestBasic.cs
Model/Activities/PartialActivityType.cs
Parsers/CentraalBeheer/CentraalBeheerParser.cs
Parsers/SymbolMapper.cs
Parsers/Trading212/Trading212Parser.cs

Fixing some integration with ghostfolio
